### code pay
# {
#  "success": true,
#  "code": "10000",
#  "message": "Success",
#  "requestId": null
#}
POST http://localhost:8080/api/v1/pay/code-pay
Content-Type: application/json

{
  "channelId": "pay.alipay",
  "propertiesId": "2021000117624946",
  "subject": "测试",
  "outTradeNo": "281738735096173188",
  "totalAmount": 1,
  "authCode": "281738735096173188"
}

### query
# {
#  "success": true,
#  "code": "10000",
#  "message": "Success",
#  "requestId": null,
#  "status": "TRADE_SUCCESS"
#}
POST http://localhost:8080/api/v1/pay/query
Content-Type: application/json

{
  "channelId": "pay.alipay",
  "propertiesId": "2021000117624946",
  "outTradeNo": "281738735096173188"
}
